import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../database/database.dart';
import 'package:intl/intl.dart';

class PdfExportService {
  static Future<void> generateBillPdf(BillMedDatabase db, int billId) async {
    final bill = await db.getBill(billId);
    final dists = await db.getAllDistributors();
    final distMap = {for (final d in dists) d.id: d};
    if (bill == null) return;

    final dist = distMap[bill.distributorId];
    final payments = await db.getPaymentsByBill(billId);
    final paid = await db.getTotalPaidForBill(billId);
    final remaining = (bill.amount - paid).clamp(0, bill.amount);

    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        margin: const pw.EdgeInsets.all(40),
        build: (ctx) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Header(
              level: 0,
              child: pw.Text('BillMed', style: pw.TextStyle(fontSize: 24, color: PdfColors.indigo)),
            ),
            pw.SizedBox(height: 4),
            pw.Text('Bill Statement', style: pw.TextStyle(fontSize: 16, color: PdfColors.grey)),
            pw.Divider(),
            pw.SizedBox(height: 12),

            // Bill info
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('Bill #${bill.billNumber}', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                    pw.Text('Date: ${DateFormat('dd/MM/yyyy').format(bill.billDate)}', style: pw.TextStyle(fontSize: 12)),
                  ],
                ),
                if (dist != null)
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text(dist.name, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                      if (dist.company != null && dist.company!.isNotEmpty)
                        pw.Text(dist.company!, style: pw.TextStyle(fontSize: 11, color: PdfColors.grey)),
                    ],
                  ),
              ],
            ),
            pw.SizedBox(height: 20),

            // Amount summary
            pw.Container(
              padding: const pw.EdgeInsets.all(16),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey300),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
              ),
              child: pw.Column(
                children: [
                  _row('Bill Amount', '₹${bill.amount.toStringAsFixed(2)}'),
                  _row('Total Paid', '₹${paid.toStringAsFixed(2)}'),
                  pw.Divider(),
                  _row('Remaining', '₹${remaining.toStringAsFixed(2)}'),
                ],
              ),
            ),
            pw.SizedBox(height: 20),

            // Payments
            if (payments.isNotEmpty) ...[
              pw.Text('Payment History', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 8),
              pw.TableHelper.fromTextArray(
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10),
                headerDecoration: pw.BoxDecoration(color: PdfColors.indigo50),
                cellStyle: const pw.TextStyle(fontSize: 10),
                headers: ['Date', 'Amount', 'Mode', 'Reference'],
                data: payments.map((p) => [
                  DateFormat('dd/MM/yyyy').format(p.paymentDate),
                  '₹${p.amount.toStringAsFixed(2)}',
                  p.mode,
                  p.referenceNo ?? '-',
                ]).toList(),
              ),
            ],

            pw.SizedBox(height: 20),
            pw.Divider(),
            pw.SizedBox(height: 8),
            pw.Text('Generated by BillMed', style: pw.TextStyle(fontSize: 9, color: PdfColors.grey)),
            pw.Text(DateFormat('dd/MM/yyyy HH:mm').format(DateTime.now()), style: pw.TextStyle(fontSize: 9, color: PdfColors.grey)),
          ],
        ),
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/Bill_${bill.billNumber}.pdf');
    await file.writeAsBytes(await pdf.save());
    await Share.shareXFiles([XFile(file.path)], text: 'Bill #${bill.billNumber}');
  }

  static Future<void> generateCaReportPdf(BillMedDatabase db) async {
    final allTxns = await db.getAllBankTransactions();
    final pdf = pw.Document();

    final totalDebit = allTxns.fold<double>(0, (s, t) => s + t.debit);
    final totalCredit = allTxns.fold<double>(0, (s, t) => s + t.credit);
    final net = totalCredit - totalDebit;

    final months = <String, Map<String, double>>{};
    for (final t in allTxns) {
      final key = '${t.txnDate.year}-${t.txnDate.month.toString().padLeft(2, '0')}';
      months.putIfAbsent(key, () => {'debit': 0.0, 'credit': 0.0});
      months[key]!['debit'] = (months[key]!['debit'] ?? 0) + t.debit;
      months[key]!['credit'] = (months[key]!['credit'] ?? 0) + t.credit;
    }

    pdf.addPage(
      pw.MultiPage(
        margin: const pw.EdgeInsets.all(40),
        header: (ctx) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('BillMed - CA Report', style: pw.TextStyle(fontSize: 22, color: PdfColors.indigo, fontWeight: pw.FontWeight.bold)),
            pw.Text('Annual Financial Summary', style: pw.TextStyle(fontSize: 14, color: PdfColors.grey)),
            pw.Divider(),
            pw.SizedBox(height: 8),
          ],
        ),
        footer: (ctx) => pw.Text('Generated on ${DateFormat('dd/MM/yyyy HH:mm').format(DateTime.now())}',
            style: pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
        build: (ctx) => [
          pw.Header(level: 1, text: 'Summary'),
          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11),
            data: [
              ['Total Debits', '₹${totalDebit.toStringAsFixed(2)}'],
              ['Total Credits', '₹${totalCredit.toStringAsFixed(2)}'],
              ['Net (Credits - Debits)', '₹${net.toStringAsFixed(2)}'],
              ['Total Transactions', '${allTxns.length}'],
            ],
          ),
          pw.SizedBox(height: 20),
          pw.Header(level: 1, text: 'Monthly Breakdown'),
          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10),
            headerDecoration: pw.BoxDecoration(color: PdfColors.indigo50),
            cellStyle: const pw.TextStyle(fontSize: 10),
            headers: ['Month', 'Debits', 'Credits', 'Net'],
            data: months.entries.map((e) => [
              e.key,
              '₹${(e.value['debit'] ?? 0).toStringAsFixed(2)}',
              '₹${(e.value['credit'] ?? 0).toStringAsFixed(2)}',
              '₹${((e.value['credit'] ?? 0) - (e.value['debit'] ?? 0)).toStringAsFixed(2)}',
            ]).toList(),
          ),
        ],
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/BillMed_CA_Report.pdf');
    await file.writeAsBytes(await pdf.save());
    await Share.shareXFiles([XFile(file.path)], text: 'CA Report');
  }

  static pw.Widget _row(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 3),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: pw.TextStyle(fontSize: 12)),
          pw.Text(value, style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }
}
